/*
 * THIS FILE IS PART OF SANDBOX, LICENSED UNDER THE
 *
 *                 GNU GENERAL PUBLIC LICENSE V3.0
 *
 * PERMISSIONS OF THIS STRONG COPYLEFT LICENSE ARE CONDITIONED ON MAKING 
 * AVAILABLE COMPLETE SOURCE CODE OF LICENSED WORKS AND MODIFICATIONS, WHICH 
 * INCLUDE LARGER WORKS USING A LICENSED WORK, UNDER THE SAME LICENSE. 
 * COPYRIGHT AND LICENSE NOTICES MUST BE PRESERVED. CONTRIBUTORS PROVIDE AN 
 * EXPRESS GRANT OF PATENT RIGHTS.
 * 
 * SANDBOX IS FREE SOFTWARE: YOU CAN REDISTRIBUTE IT AND/OR MODIFY IT UNDER 
 * THE TERMS OF THE GNU GENERAL PUBLIC LICENSE AS PUBLISHED BY THE FREE SOFTWARE 
 * FOUNDATION, EITHER VERSION 3 OF THE LICENSE, OR (AT YOUR OPTION) ANY LATER 
 * VERSION.
 * 
 * SANDBOX IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT WITHOUT ANY
 * WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF MERCHANTABILITY OR FITNESS FOR
 * A PARTICULAR PURPOSE. SEE THE GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
 * 
 * YOU SHOULD HAVE RECEIVED A COPY OF THE GNU GENERAL PUBLIC LICENSE ALONG WITH 
 * SANDBOX. IF NOT, SEE <HTTPS://WWW.GNU.ORG/LICENSES/>. 
 */

/***
 * \file main.cpp
 * 
 * File with the entry point (main) function.
 * 
 * \author Phillippe Samer <samer@uib.no>
 * \date 04.02.2025
 */

#include "x.h"

#include <iostream>

using namespace std;

int main()
{
	return 0;
}
